### ISSUE TITLE
[Feat] LoginScreen 구현

### ISSUE THREAD

**Issue by nahy-512** [nahy-512/Instagram_clone_coding#5]
- iOS

![IMG_0410](https://github.com/nahy-512/Instagram_clone_coding/assets/101113025/c2cd1d36-b473-41d3-a536-6cd7c0ece65e) | ![IMG_0411](https://github.com/nahy-512/Instagram_clone_coding/assets/101113025/cf05c3e8-c9d7-41b5-b77c-3f709ba16953) | ![IMG_0414](https://github.com/nahy-512/Instagram_clone_coding/assets/101113025/c45fc480-1b0e-4b37-b042-8e778dbf0f52)
---|---|---|

- Android

![IMG_0410](https://media.discordapp.net/attachments/1124558739211558993/1219135299712454676/Screenshot_20240318-130738_Instagram.jpg?ex=660a3339&is=65f7be39&hm=46788ad0715dc594d3c88c34594c69d447f92723761f9b6502bb7d7e85cd6193&=&format=webp&width=546&height=1122) | ![IMG_0411](https://media.discordapp.net/attachments/1124558739211558993/1219135299922296932/Screenshot_20240318-130753_Instagram.jpg?ex=660a3339&is=65f7be39&hm=e47d5eaf93678bcc39597d622c3d59f78ba8bee755a070e01ae1ffbf45a11a1a&=&format=webp&width=546&height=1122) | ![IMG_0414](https://media.discordapp.net/attachments/1124558739211558993/1219135300274622594/Screenshot_20240318-130803_Instagram.jpg?ex=660a333a&is=65f7be3a&hm=b2543c113edd7d0347b0df49090a79368ac5d2f8c6c228aa772b9edd9f80cbc1&=&format=webp&width=546&height=1122)
---|---|---|

## Description
Instagram의 LoginScreen을 구현한다.

## To-do
- [x] 루트 변경
- [x] UI 구현
- [x] 사용자 이름, 이메일 주소 또는 휴대폰 번호 TextField
  - [x] 포커스되었을 때 검정 border
- [x] 비밀번호 TextField
  - [x] 비밀번호 보기 및 숨기기

## ETC
- [ ] TextField 포커스되었을 때만 우측 버튼 표시하기
- [ ] 키보드 Enter 클릭 시 다음 TextField로 이동
- [ ] 키보드 등장할 때의 처리
