### ISSUE TITLE
[Fix] 로그인 화면 UI 변경

### ISSUE THREAD

**Issue by nahy-512** [nahy-512/Instagram_clone_coding#8]
![IMG_0550](https://github.com/nahy-512/Flutter_Instagram/assets/101113025/d5f237d9-3234-4de7-b7c0-968775315d66) 기본 | ![IMG_0551](https://github.com/nahy-512/Flutter_Instagram/assets/101113025/b49948b3-d819-4d5b-b88a-86a9206458ec) 비밀번호 입력 | ![Group 190](https://github.com/nahy-512/Flutter_Instagram/assets/101113025/e53f4080-76bc-471c-9a52-fd08ad7e98c0) 입력 후
---|---|---|

## Description
기존 계정이 있을 때 나오는 로그인화면 말고, 계정 설정 -> 계정 추가 -> '기존 계정으로 로그인' 선택 시 나오는 로그인 화면 구현

## To-do
작업해야 하는 투두리스트를 작성해 주세요.
- [x] TextField
   - [x] 이름 입력 clear 버튼
   - [x] 비밀번호 보기/숨기기
- [x] 로그인 버튼 활성화
- [ ] 키보드에 따른 처리
